# Generated by Django 3.2 on 2021-04-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'Otro'), ('3', 'Economista'), ('0', 'Contador'), ('1', 'Administrador')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
