# Generated by Django 3.2 on 2021-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210420_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.Habilidades'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'Administrador'), ('4', 'Otro'), ('3', 'Economista'), ('0', 'Contador')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
