# Generated by Django 3.2 on 2021-04-20 15:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20210420_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('4', 'Otro'), ('0', 'Contador'), ('3', 'Economista'), ('1', 'Administrador')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
