# Generated by Django 3.2 on 2021-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20210420_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'Administrador'), ('3', 'Economista'), ('0', 'Contador'), ('4', 'Otro')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
