# Generated by Django 3.2 on 2021-04-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_auto_20210421_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('3', 'Economista'), ('1', 'Administrador'), ('0', 'Contador'), ('4', 'Otro')], max_length=1, verbose_name='Trabajo'),
        ),
    ]
